FROM golang:1.19.1-alpine3.16 as builder

WORKDIR /home
COPY . .

RUN go env -w GO111MODULE=on \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go env -w CGO_ENABLED=0 \
    && go env \
    && go mod tidy \
    && cd rpc \
    && go build -ldflags="-s -w" -o /home/rpc/load_rpc load.go

FROM alpine:latest

LABEL MAINTAINER="RyanSU@yuansu.china.work@gmail.com"

WORKDIR /home

COPY --from=builder /home/rpc/load_rpc ./
COPY --from=builder /home/rpc/etc/load.yaml ./

EXPOSE 9101
ENTRYPOINT ./load_rpc -f core.yaml