// Code generated by goctl. DO NOT EDIT.
// Source: load.proto

package server

import (
	"context"

	"github.com/vwenkk/load/rpc/internal/logic/base"
	"github.com/vwenkk/load/rpc/internal/svc"
	"github.com/vwenkk/load/rpc/types/load"
)

type LoadServer struct {
	svcCtx *svc.ServiceContext
	load.UnimplementedLoadServer
}

func NewLoadServer(svcCtx *svc.ServiceContext) *LoadServer {
	return &LoadServer{
		svcCtx: svcCtx,
	}
}

func (s *LoadServer) InitDatabase(ctx context.Context, in *load.Empty) (*load.BaseResp, error) {
	l := base.NewInitDatabaseLogic(ctx, s.svcCtx)
	return l.InitDatabase(in)
}
