// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	base "github.com/vwenkk/load/api/internal/handler/base"
	group "github.com/vwenkk/load/api/internal/handler/group"
	"github.com/vwenkk/load/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/init/database",
				Handler: base.InitDatabaseHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(

		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/group/create",
				Handler: group.CreateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/group/update",
				Handler: group.UpdateGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/group/delete",
				Handler: group.DeleteGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/group/list",
				Handler: group.GetGroupListHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/group",
				Handler: group.GetGroupByIdHandler(serverCtx),
			},
		},
	)
}
